# Generated by Django 4.1.3 on 2023-09-27 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RetailsApis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailsAccountSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountSystemName', models.CharField(max_length=500, verbose_name='Account System Name')),
            ],
            options={
                'verbose_name_plural': 'AccountSystem',
            },
        ),
        migrations.CreateModel(
            name='RetailsBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=500, verbose_name='Code')),
                ('Name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Retails BOM',
            },
        ),
        migrations.CreateModel(
            name='RetailsBOMFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BOMCodeFile', models.FileField(upload_to='media/BOMFiles', verbose_name='BOM Code File')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Retails BOM Files',
            },
        ),
        migrations.CreateModel(
            name='RetailsBusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=500, verbose_name='Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Retails Business Unit',
            },
        ),
        migrations.CreateModel(
            name='RetailsEventA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventDescription', models.TextField(max_length=1000, verbose_name='Event Description')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Retails Event A',
            },
        ),
        migrations.CreateModel(
            name='RetailsEventB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventDescription', models.TextField(max_length=1000, verbose_name='Event Description')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Retails Event B',
            },
        ),
        migrations.CreateModel(
            name='RetailsEventCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=200, verbose_name='Category Name')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Retails Event Categories',
            },
        ),
        migrations.CreateModel(
            name='RetailsEventCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=500, verbose_name='Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Retails Event Code',
            },
        ),
        migrations.CreateModel(
            name='RetailsGridDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GridDimensionsName', models.CharField(max_length=500, verbose_name='Grid Dimensions')),
            ],
            options={
                'verbose_name_plural': 'GridDimensions',
            },
        ),
        migrations.CreateModel(
            name='RetailsLocationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=500, verbose_name='Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('BusinessUnit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RetailsApis.retailsbusinessunit', verbose_name='Business Unit')),
            ],
            options={
                'verbose_name_plural': 'Retails Location Code',
            },
        ),
        migrations.CreateModel(
            name='RetailsProcessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProcesId', models.CharField(max_length=500, verbose_name='Proces Id')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Retails Process Config',
            },
        ),
        migrations.CreateModel(
            name='RetailsSigninTimeout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SigninTimeoutName', models.CharField(max_length=500, verbose_name='Signin Timeout Name')),
            ],
            options={
                'verbose_name_plural': 'SigninTimeout',
            },
        ),
        migrations.CreateModel(
            name='RetailsStoreBinCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreBinCode', models.CharField(max_length=500, verbose_name='Store Bin Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('CardNo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Card No')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Retails Store Bin Code',
            },
        ),
        migrations.CreateModel(
            name='RetailsUOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UOMShortCode', models.CharField(max_length=500, verbose_name='UOM Short Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Retails UOM',
            },
        ),
        migrations.CreateModel(
            name='RetailsVatRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RateName', models.CharField(max_length=500, verbose_name='Rate Name')),
            ],
            options={
                'verbose_name_plural': 'VatRate',
            },
        ),
        migrations.CreateModel(
            name='RetailsStoreCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=500, verbose_name='Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RetailsApis.retailslocationcode', verbose_name='Store Location')),
                ('Process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RetailsApis.retailsprocessconfig', verbose_name='Process')),
            ],
            options={
                'verbose_name_plural': 'Retails Store Code',
            },
        ),
        migrations.CreateModel(
            name='RetailsEventAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlertID', models.CharField(max_length=500, verbose_name='Code')),
                ('ReceivedBy', models.EmailField(blank=True, max_length=1000, null=True, verbose_name='Received By')),
                ('PhoneNo', models.CharField(blank=True, default='+255', max_length=14, null=True, verbose_name='Phone No')),
                ('Message', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Message')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RetailsApis.retailseventcategories', verbose_name='Category')),
                ('EventA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RetailsApis.retailseventa', verbose_name='Event A')),
                ('EventB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RetailsApis.retailseventb', verbose_name='Event B')),
            ],
            options={
                'verbose_name_plural': 'Retails Event Code',
            },
        ),
        migrations.AddField(
            model_name='retailsdrinksproducts',
            name='StoreBinCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RetailsApis.retailsstorebincode', verbose_name='Store Bin Code'),
        ),
        migrations.AddField(
            model_name='retailsdrinksproducts',
            name='StoreCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RetailsApis.retailsstorecode', verbose_name='Store Code'),
        ),
        migrations.AddField(
            model_name='retailsfoodproducts',
            name='StoreBinCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RetailsApis.retailsstorebincode', verbose_name='Store Bin Code'),
        ),
        migrations.AddField(
            model_name='retailsfoodproducts',
            name='StoreCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RetailsApis.retailsstorecode', verbose_name='Store Code'),
        ),
    ]
