# Generated by Django 4.1.3 on 2023-09-28 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RetailsApis', '0002_retailsaccountsystem_retailsbom_retailsbomfiles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailsProductsUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit', models.CharField(max_length=500, verbose_name='Unit')),
                ('Description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Retails Products Unit',
            },
        ),
        migrations.AddField(
            model_name='retailsdrinksproducts',
            name='Unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RetailsApis.retailsproductsunit', verbose_name='Product Unit'),
        ),
        migrations.AddField(
            model_name='retailsfoodproducts',
            name='Unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RetailsApis.retailsproductsunit', verbose_name='Product Unit'),
        ),
    ]
