# Generated by Django 4.1.3 on 2023-10-02 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RetailsApis', '0005_retailssuppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailsTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TableNumber', models.CharField(blank=True, default='Table 20', max_length=500, null=True, verbose_name='Table Number')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Retails Tables',
            },
        ),
        migrations.AddField(
            model_name='retailsdrinkscartitems',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RetailsApis.retailstables'),
        ),
        migrations.AddField(
            model_name='retailsdrinksorderitems',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RetailsApis.retailstables'),
        ),
        migrations.AddField(
            model_name='retailsfoodcartitems',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RetailsApis.retailstables'),
        ),
        migrations.AddField(
            model_name='retailsfoodorderitems',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RetailsApis.retailstables'),
        ),
    ]
