# Generated by Django 4.1.3 on 2023-10-05 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RetailsApis', '0007_retailsdrinkscartitems_customeraddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailsCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerFullName', models.CharField(max_length=500, verbose_name='Customer Full Name')),
                ('PhoneNumber', models.CharField(blank=True, default='+255', max_length=14, null=True, verbose_name='Phone Number')),
                ('CustomerAddress', models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Address')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Retails Customers',
            },
        ),
        migrations.RemoveField(
            model_name='retailsdrinkscartitems',
            name='CustomerAddress',
        ),
        migrations.RemoveField(
            model_name='retailsdrinkscartitems',
            name='CustomerFullName',
        ),
        migrations.RemoveField(
            model_name='retailsdrinkscartitems',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='retailsdrinksorderitems',
            name='CustomerAddress',
        ),
        migrations.RemoveField(
            model_name='retailsdrinksorderitems',
            name='CustomerFullName',
        ),
        migrations.RemoveField(
            model_name='retailsdrinksorderitems',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='retailsfoodcartitems',
            name='CustomerAddress',
        ),
        migrations.RemoveField(
            model_name='retailsfoodcartitems',
            name='CustomerFullName',
        ),
        migrations.RemoveField(
            model_name='retailsfoodcartitems',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='retailsfoodorderitems',
            name='CustomerAddress',
        ),
        migrations.RemoveField(
            model_name='retailsfoodorderitems',
            name='CustomerFullName',
        ),
        migrations.RemoveField(
            model_name='retailsfoodorderitems',
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='retailsdrinkscartitems',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RetailsApis.retailscustomers'),
        ),
        migrations.AddField(
            model_name='retailsdrinksorderitems',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RetailsApis.retailscustomers'),
        ),
        migrations.AddField(
            model_name='retailsfoodcartitems',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RetailsApis.retailscustomers'),
        ),
        migrations.AddField(
            model_name='retailsfoodorderitems',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RetailsApis.retailscustomers'),
        ),
    ]
