# Generated by Django 4.1.3 on 2023-09-27 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantAccountSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountSystemName', models.CharField(max_length=500, verbose_name='Account System Name')),
            ],
            options={
                'verbose_name_plural': 'AccountSystem',
            },
        ),
        migrations.CreateModel(
            name='RestaurantBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=500, verbose_name='Code')),
                ('Name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurant BOM',
            },
        ),
        migrations.CreateModel(
            name='RestaurantBOMFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BOMCodeFile', models.FileField(upload_to='media/BOMFiles', verbose_name='BOM Code File')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurant BOM Files',
            },
        ),
        migrations.CreateModel(
            name='RestaurantBusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=500, verbose_name='Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurant Business Unit',
            },
        ),
        migrations.CreateModel(
            name='RestaurantEventA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventDescription', models.TextField(max_length=1000, verbose_name='Event Description')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurant Event A',
            },
        ),
        migrations.CreateModel(
            name='RestaurantEventB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventDescription', models.TextField(max_length=1000, verbose_name='Event Description')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurant Event B',
            },
        ),
        migrations.CreateModel(
            name='RestaurantEventCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=200, verbose_name='Category Name')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurant Event Categories',
            },
        ),
        migrations.CreateModel(
            name='RestaurantEventCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=500, verbose_name='Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurant Event Code',
            },
        ),
        migrations.CreateModel(
            name='RestaurantGridDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GridDimensionsName', models.CharField(max_length=500, verbose_name='Grid Dimensions')),
            ],
            options={
                'verbose_name_plural': 'GridDimensions',
            },
        ),
        migrations.CreateModel(
            name='RestaurantLocationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=500, verbose_name='Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('BusinessUnit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RestaurantApis.restaurantbusinessunit', verbose_name='Business Unit')),
            ],
            options={
                'verbose_name_plural': 'Restaurant Location Code',
            },
        ),
        migrations.CreateModel(
            name='RestaurantProcessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProcesId', models.CharField(max_length=500, verbose_name='Proces Id')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurant Process Config',
            },
        ),
        migrations.CreateModel(
            name='RestaurantSigninTimeout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SigninTimeoutName', models.CharField(max_length=500, verbose_name='Signin Timeout Name')),
            ],
            options={
                'verbose_name_plural': 'SigninTimeout',
            },
        ),
        migrations.CreateModel(
            name='RestaurantStoreBinCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreBinCode', models.CharField(max_length=500, verbose_name='Store Bin Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('CardNo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Card No')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurant Store Bin Code',
            },
        ),
        migrations.CreateModel(
            name='RestaurantUOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UOMShortCode', models.CharField(max_length=500, verbose_name='UOM Short Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurant UOM',
            },
        ),
        migrations.CreateModel(
            name='RestaurantVatRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RateName', models.CharField(max_length=500, verbose_name='Rate Name')),
            ],
            options={
                'verbose_name_plural': 'VatRate',
            },
        ),
        migrations.CreateModel(
            name='RestaurantStoreCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=500, verbose_name='Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RestaurantApis.restaurantlocationcode', verbose_name='Store Location')),
                ('Process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RestaurantApis.restaurantprocessconfig', verbose_name='Process')),
            ],
            options={
                'verbose_name_plural': 'Restaurant Store Code',
            },
        ),
        migrations.CreateModel(
            name='RestaurantEventAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlertID', models.CharField(max_length=500, verbose_name='Code')),
                ('ReceivedBy', models.EmailField(blank=True, max_length=1000, null=True, verbose_name='Received By')),
                ('PhoneNo', models.CharField(blank=True, default='+255', max_length=14, null=True, verbose_name='Phone No')),
                ('Message', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Message')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RestaurantApis.restauranteventcategories', verbose_name='Category')),
                ('EventA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestaurantApis.restauranteventa', verbose_name='Event A')),
                ('EventB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestaurantApis.restauranteventb', verbose_name='Event B')),
            ],
            options={
                'verbose_name_plural': 'Restaurant Event Code',
            },
        ),
        migrations.AddField(
            model_name='restaurantdrinksproducts',
            name='StoreBinCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RestaurantApis.restaurantstorebincode', verbose_name='Store Bin Code'),
        ),
        migrations.AddField(
            model_name='restaurantdrinksproducts',
            name='StoreCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestaurantApis.restaurantstorecode', verbose_name='Store Code'),
        ),
        migrations.AddField(
            model_name='restaurantfoodproducts',
            name='StoreBinCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RestaurantApis.restaurantstorebincode', verbose_name='Store Bin Code'),
        ),
        migrations.AddField(
            model_name='restaurantfoodproducts',
            name='StoreCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestaurantApis.restaurantstorecode', verbose_name='Store Code'),
        ),
    ]
