# Generated by Django 4.1.3 on 2023-09-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApis', '0003_restaurantproductsunit_restaurantdrinksproducts_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdrinksorder',
            name='order_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='restaurantdrinksorderitems',
            name='order_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='restaurantfoodorder',
            name='order_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='restaurantfoodorderitems',
            name='order_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Status'),
        ),
    ]
