# Generated by Django 4.1.3 on 2023-10-02 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApis', '0005_restaurantsuppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TableNumber', models.CharField(blank=True, default='Table 20', max_length=500, null=True, verbose_name='Table Number')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurant Tables',
            },
        ),
        migrations.AddField(
            model_name='restaurantdrinkscartitems',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RestaurantApis.restauranttables'),
        ),
        migrations.AddField(
            model_name='restaurantdrinksorderitems',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RestaurantApis.restauranttables'),
        ),
        migrations.AddField(
            model_name='restaurantfoodcartitems',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RestaurantApis.restauranttables'),
        ),
        migrations.AddField(
            model_name='restaurantfoodorderitems',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RestaurantApis.restauranttables'),
        ),
    ]
