# Generated by Django 4.1.3 on 2023-10-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApis', '0006_restauranttables_restaurantdrinkscartitems_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdrinkscartitems',
            name='CustomerAddress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Address'),
        ),
        migrations.AddField(
            model_name='restaurantdrinkscartitems',
            name='CustomerFullName',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Customer Full Name'),
        ),
        migrations.AddField(
            model_name='restaurantdrinkscartitems',
            name='PhoneNumber',
            field=models.CharField(blank=True, default='+255', max_length=14, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='restaurantdrinksorderitems',
            name='CustomerAddress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Address'),
        ),
        migrations.AddField(
            model_name='restaurantdrinksorderitems',
            name='CustomerFullName',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Customer Full Name'),
        ),
        migrations.AddField(
            model_name='restaurantdrinksorderitems',
            name='PhoneNumber',
            field=models.CharField(blank=True, default='+255', max_length=14, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='restaurantfoodcartitems',
            name='CustomerAddress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Address'),
        ),
        migrations.AddField(
            model_name='restaurantfoodcartitems',
            name='CustomerFullName',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Customer Full Name'),
        ),
        migrations.AddField(
            model_name='restaurantfoodcartitems',
            name='PhoneNumber',
            field=models.CharField(blank=True, default='+255', max_length=14, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='restaurantfoodorderitems',
            name='CustomerAddress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Address'),
        ),
        migrations.AddField(
            model_name='restaurantfoodorderitems',
            name='CustomerFullName',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Customer Full Name'),
        ),
        migrations.AddField(
            model_name='restaurantfoodorderitems',
            name='PhoneNumber',
            field=models.CharField(blank=True, default='+255', max_length=14, null=True, verbose_name='Phone Number'),
        ),
    ]
