# Generated by Django 4.1.3 on 2023-09-25 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountSystemName', models.CharField(max_length=500, verbose_name='Account System Name')),
            ],
            options={
                'verbose_name_plural': 'AccountSystem',
            },
        ),
        migrations.CreateModel(
            name='GridDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GridDimensionsName', models.CharField(max_length=500, verbose_name='Grid Dimensions')),
            ],
            options={
                'verbose_name_plural': 'GridDimensions',
            },
        ),
        migrations.CreateModel(
            name='HotelBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=500, verbose_name='Code')),
                ('Name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel BOM',
            },
        ),
        migrations.CreateModel(
            name='HotelBOMFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BOMCodeFile', models.FileField(upload_to='media/BOMFiles', verbose_name='BOM Code File')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel BOM Files',
            },
        ),
        migrations.CreateModel(
            name='HotelBusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=500, verbose_name='Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Business Unit',
            },
        ),
        migrations.CreateModel(
            name='HotelCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerFullName', models.CharField(max_length=500, verbose_name='Customer Full Name')),
                ('PhoneNumber', models.CharField(blank=True, default='+255', max_length=14, null=True, verbose_name='Phone Number')),
                ('CustomerAddress', models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Address')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Customers',
            },
        ),
        migrations.CreateModel(
            name='HotelDrinksCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('total_price', models.FloatField(default=0, verbose_name='Total Price')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Drinks Cart',
            },
        ),
        migrations.CreateModel(
            name='HotelDrinksCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100, verbose_name='Category Name')),
                ('Store', models.IntegerField(blank=True, null=True, verbose_name='Quantity in Store')),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='media/DrinksImages/', verbose_name='Category Image')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Drinks Categories',
            },
        ),
        migrations.CreateModel(
            name='HotelDrinksOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(verbose_name='Total Price')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hoteldrinkscart')),
            ],
            options={
                'verbose_name_plural': 'Hotel Drinks Orders',
            },
        ),
        migrations.CreateModel(
            name='HotelEventA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventDescription', models.TextField(max_length=1000, verbose_name='Event Description')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Event A',
            },
        ),
        migrations.CreateModel(
            name='HotelEventB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventDescription', models.TextField(max_length=1000, verbose_name='Event Description')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Event B',
            },
        ),
        migrations.CreateModel(
            name='HotelEventCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=200, verbose_name='Category Name')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Event Categories',
            },
        ),
        migrations.CreateModel(
            name='HotelEventCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=500, verbose_name='Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Event Code',
            },
        ),
        migrations.CreateModel(
            name='HotelFoodCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('total_price', models.FloatField(default=0, verbose_name='Total Price')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Food Cart',
            },
        ),
        migrations.CreateModel(
            name='HotelFoodCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100, verbose_name='Category Name')),
                ('Store', models.IntegerField(blank=True, null=True, verbose_name='Quantity in Store')),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='media/FoodImages/', verbose_name='Category Image')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Food Categories',
            },
        ),
        migrations.CreateModel(
            name='HotelFoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(verbose_name='Total Price')),
                ('created', models.DateField(auto_now_add=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelfoodcart')),
            ],
            options={
                'verbose_name_plural': 'Hotel Food Orders',
            },
        ),
        migrations.CreateModel(
            name='HotelInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100, verbose_name='Category')),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='media/HotelInventoryImages/', verbose_name='Category Image')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Inventory',
            },
        ),
        migrations.CreateModel(
            name='HotelLocationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=500, verbose_name='Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('BusinessUnit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hotelbusinessunit', verbose_name='Business Unit')),
            ],
            options={
                'verbose_name_plural': 'Hotel Location Code',
            },
        ),
        migrations.CreateModel(
            name='HotelProcessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProcesId', models.CharField(max_length=500, verbose_name='Proces Id')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Process Config',
            },
        ),
        migrations.CreateModel(
            name='HotelRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomName', models.CharField(default='Room 1', max_length=100, verbose_name='Room Name')),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('RoomFloor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Room Floor')),
                ('RoomStatus', models.BooleanField(blank=True, default=False, max_length=100, null=True, verbose_name='Room Status')),
                ('ProductQuantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantity')),
                ('InitialProductQuantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='Initial Quantity')),
                ('RoomImage', models.ImageField(blank=True, null=True, upload_to='media/RoomImages/', verbose_name='Room Image')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Rooms',
            },
        ),
        migrations.CreateModel(
            name='HotelRoomsCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('total_price', models.FloatField(default=0, verbose_name='Total Price')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Rooms Cart',
            },
        ),
        migrations.CreateModel(
            name='HotelRoomsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(verbose_name='Total Price')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelroomscart')),
            ],
            options={
                'verbose_name_plural': 'Hotel Rooms Orders',
            },
        ),
        migrations.CreateModel(
            name='HotelStoreBinCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreBinCode', models.CharField(max_length=500, verbose_name='Store Bin Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('CardNo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Card No')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Store Bin Code',
            },
        ),
        migrations.CreateModel(
            name='HotelUOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UOMShortCode', models.CharField(max_length=500, verbose_name='UOM Short Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel UOM',
            },
        ),
        migrations.CreateModel(
            name='RestaurantCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerFullName', models.CharField(max_length=500, verbose_name='Customer Full Name')),
                ('PhoneNumber', models.CharField(blank=True, default='+255', max_length=14, null=True, verbose_name='Phone Number')),
                ('CustomerAddress', models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Address')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurant Customers',
            },
        ),
        migrations.CreateModel(
            name='RestaurantDrinksCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100, verbose_name='Category Name')),
                ('Store', models.IntegerField(blank=True, null=True, verbose_name='Quantity in Store')),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='media/DrinksImages/', verbose_name='Category Image')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurant Drinks Categories',
            },
        ),
        migrations.CreateModel(
            name='RestaurantFoodCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100, verbose_name='Category Name')),
                ('Store', models.IntegerField(blank=True, null=True, verbose_name='Quantity in Store')),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='media/FoodImages/', verbose_name='Category Image')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurant Food Categories',
            },
        ),
        migrations.CreateModel(
            name='RestaurantInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100, verbose_name='Category')),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='media/RestaurantInventoryImages/', verbose_name='Category Image')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurant Inventory',
            },
        ),
        migrations.CreateModel(
            name='RetailsCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerFullName', models.CharField(max_length=500, verbose_name='Customer Full Name')),
                ('PhoneNumber', models.CharField(blank=True, default='+255', max_length=14, null=True, verbose_name='Phone Number')),
                ('CustomerAddress', models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Address')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Retails Customers',
            },
        ),
        migrations.CreateModel(
            name='RetailsDrinksCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100, verbose_name='Category Name')),
                ('Store', models.IntegerField(blank=True, null=True, verbose_name='Quantity in Store')),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='media/DrinksImages/', verbose_name='Category Image')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Retails Drinks Categories',
            },
        ),
        migrations.CreateModel(
            name='RetailsFoodCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100, verbose_name='Category Name')),
                ('Store', models.IntegerField(blank=True, null=True, verbose_name='Quantity in Store')),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='media/FoodImages/', verbose_name='Category Image')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Retails Food Categories',
            },
        ),
        migrations.CreateModel(
            name='RetailsInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100, verbose_name='Category')),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='media/RetailsInventoryImages/', verbose_name='Category Image')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Retails Inventory',
            },
        ),
        migrations.CreateModel(
            name='RoomsClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomClass', models.CharField(max_length=100, verbose_name='Room Class')),
                ('Quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Rooms Classes',
            },
        ),
        migrations.CreateModel(
            name='SigninTimeout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SigninTimeoutName', models.CharField(max_length=500, verbose_name='Signin Timeout Name')),
            ],
            options={
                'verbose_name_plural': 'SigninTimeout',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=500, verbose_name='Role Name')),
            ],
            options={
                'verbose_name_plural': 'UserRole',
            },
        ),
        migrations.CreateModel(
            name='VatRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RateName', models.CharField(max_length=500, verbose_name='Rate Name')),
            ],
            options={
                'verbose_name_plural': 'VatRate',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='user name')),
                ('middle_name', models.CharField(max_length=100, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('company_name', models.CharField(max_length=100, verbose_name='company name')),
                ('phone', models.CharField(max_length=15, verbose_name='phone')),
                ('UserCodes', models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='User Codes')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('AddressLine1', models.CharField(blank=True, max_length=500, null=True, verbose_name='Address Line 1')),
                ('AddressLine2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Address Line 2')),
                ('VatNo', models.CharField(blank=True, max_length=500, null=True, verbose_name='VAT No')),
                ('VatEnabled', models.BooleanField(blank=True, default='True', null=True, verbose_name='VAT Enabled')),
                ('ApprovedNeeded', models.BooleanField(blank=True, default='False', null=True, verbose_name='Approved Needed')),
                ('PrintOrderItems', models.BooleanField(blank=True, default='True', null=True, verbose_name='Print Order Items')),
                ('PrintConfirmedOrderSlip', models.BooleanField(blank=True, default='False', null=True, verbose_name='Print Confirmed Order Slip')),
                ('StockClosingTime', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Stock Closing Time')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_hotel_user', models.BooleanField(default=False)),
                ('is_restaurant_user', models.BooleanField(default=False)),
                ('is_retails_user', models.BooleanField(default=False)),
                ('hide_email', models.BooleanField(default=True)),
                ('AccountSystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.accountsystem', verbose_name='Account System')),
                ('GridDimensions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.griddimensions', verbose_name='Grid Dimensions')),
                ('SigninTimeout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.signintimeout', verbose_name='Signin Timeout')),
                ('UserRole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.userrole', verbose_name='User Role')),
                ('VatRate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.vatrate', verbose_name='VAT Rate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotelStoreCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=500, verbose_name='Code')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hotellocationcode', verbose_name='Store Location')),
                ('Process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hotelprocessconfig', verbose_name='Process')),
            ],
            options={
                'verbose_name_plural': 'Hotel Store Code',
            },
        ),
        migrations.CreateModel(
            name='HotelRoomsOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('CustomerFullName', models.CharField(blank=True, max_length=500, null=True, verbose_name='Customer Full Name')),
                ('PhoneNumber', models.CharField(blank=True, default='+255', max_length=14, null=True, verbose_name='Phone Number')),
                ('CustomerAddress', models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Address')),
                ('DaysNumber', models.IntegerField(blank=True, null=True, verbose_name='Number of Days')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelroomsorder')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelrooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hotel Rooms Orders Items',
            },
        ),
        migrations.AddField(
            model_name='hotelroomsorder',
            name='orderItems',
            field=models.ManyToManyField(to='HotelApis.hotelroomsorderitems'),
        ),
        migrations.AddField(
            model_name='hotelroomsorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HotelRoomsCartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('CustomerFullName', models.CharField(max_length=500, verbose_name='Customer Full Name')),
                ('PhoneNumber', models.CharField(blank=True, default='+255', max_length=14, null=True, verbose_name='Phone Number')),
                ('CustomerAddress', models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Address')),
                ('DaysNumber', models.IntegerField(blank=True, null=True, verbose_name='Number of Days')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelroomscart')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelrooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hotel Rooms Cart Items',
            },
        ),
        migrations.AddField(
            model_name='hotelroomscart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelrooms',
            name='RoomClass',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.roomsclasses', verbose_name='Room Class'),
        ),
        migrations.CreateModel(
            name='HotelFoodProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='Wali', max_length=100, verbose_name='Product Name')),
                ('product_second_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Product Second Name')),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('ProductQuantity', models.IntegerField(blank=True, null=True, verbose_name='Product Quantity')),
                ('InitialProductQuantity', models.IntegerField(blank=True, null=True, verbose_name='Initial Product Quantity')),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='media/HotelInventoryImages/', verbose_name='Category Image')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('productCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelfoodcategories', verbose_name='Product Category')),
            ],
            options={
                'verbose_name_plural': 'Hotel Food Products',
            },
        ),
        migrations.CreateModel(
            name='HotelFoodOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelfoodorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelfoodproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hotel Food Orders Items',
            },
        ),
        migrations.AddField(
            model_name='hotelfoodorder',
            name='orderItems',
            field=models.ManyToManyField(blank=True, null=True, to='HotelApis.hotelfoodorderitems'),
        ),
        migrations.AddField(
            model_name='hotelfoodorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HotelFoodCartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelfoodcart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelfoodproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hotel Food Cart Items',
            },
        ),
        migrations.AddField(
            model_name='hotelfoodcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HotelEventAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlertID', models.CharField(max_length=500, verbose_name='Code')),
                ('ReceivedBy', models.EmailField(blank=True, max_length=1000, null=True, verbose_name='Received By')),
                ('PhoneNo', models.CharField(blank=True, default='+255', max_length=14, null=True, verbose_name='Phone No')),
                ('Message', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Message')),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=200, null=True, verbose_name='Status')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hoteleventcategories', verbose_name='Category')),
                ('EventA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hoteleventa', verbose_name='Event A')),
                ('EventB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hoteleventb', verbose_name='Event B')),
            ],
            options={
                'verbose_name_plural': 'Hotel Event Code',
            },
        ),
        migrations.CreateModel(
            name='HotelDrinksProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='Sayona', max_length=100, verbose_name='Product Name')),
                ('product_second_name', models.CharField(blank=True, default='Big', max_length=100, null=True, verbose_name='Product Second Name')),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('ProductQuantity', models.IntegerField(blank=True, null=True, verbose_name='Product Quantity')),
                ('InitialProductQuantity', models.IntegerField(blank=True, null=True, verbose_name='Initial Product Quantity')),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='media/ProductsImages/', verbose_name='Category Image')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('productCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hoteldrinkscategories', verbose_name='Product Category')),
            ],
            options={
                'verbose_name_plural': 'Hotel Drinks Products',
            },
        ),
        migrations.CreateModel(
            name='HotelDrinksOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hoteldrinksorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hoteldrinksproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hotel Drinks Orders Items',
            },
        ),
        migrations.AddField(
            model_name='hoteldrinksorder',
            name='orderItems',
            field=models.ManyToManyField(to='HotelApis.hoteldrinksorderitems'),
        ),
        migrations.AddField(
            model_name='hoteldrinksorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HotelDrinksCartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hoteldrinkscart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hoteldrinksproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hotel Drinks Cart Items',
            },
        ),
        migrations.AddField(
            model_name='hoteldrinkscart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
