# Generated by Django 4.1.3 on 2023-09-27 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldrinksproducts',
            name='StoreBinCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hotelstorebincode', verbose_name='Store Bin Code'),
        ),
        migrations.AddField(
            model_name='hoteldrinksproducts',
            name='StoreCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelstorecode', verbose_name='Store Code'),
        ),
        migrations.AddField(
            model_name='hotelfoodproducts',
            name='StoreBinCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hotelstorebincode', verbose_name='Store Bin Code'),
        ),
        migrations.AddField(
            model_name='hotelfoodproducts',
            name='StoreCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelstorecode', verbose_name='Store Code'),
        ),
    ]
