# Generated by Django 4.1.3 on 2023-09-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0003_hotelproductsunit_hoteldrinksproducts_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelfoodorder',
            name='order_stautus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='hotelfoodorderitems',
            name='order_stautus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
