# Generated by Django 4.1.3 on 2023-09-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0005_remove_hotelfoodorder_order_stautus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelfoodorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
