# Generated by Django 4.1.3 on 2023-10-02 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0007_hotelsuppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TableNumber', models.CharField(blank=True, default='Table 20', max_length=500, null=True, verbose_name='Table Number')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Tables',
            },
        ),
        migrations.AddField(
            model_name='hoteldrinkscartitems',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hotelrooms'),
        ),
        migrations.AddField(
            model_name='hoteldrinksorderitems',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hotelrooms'),
        ),
        migrations.AddField(
            model_name='hotelfoodcartitems',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hotelrooms'),
        ),
        migrations.AddField(
            model_name='hotelfoodorderitems',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hotelrooms'),
        ),
        migrations.AddField(
            model_name='hoteldrinkscartitems',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hoteltables'),
        ),
        migrations.AddField(
            model_name='hoteldrinksorderitems',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hoteltables'),
        ),
        migrations.AddField(
            model_name='hotelfoodcartitems',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hoteltables'),
        ),
        migrations.AddField(
            model_name='hotelfoodorderitems',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hoteltables'),
        ),
        migrations.AddField(
            model_name='hotelroomscartitems',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hoteltables'),
        ),
        migrations.AddField(
            model_name='hotelroomsorderitems',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hoteltables'),
        ),
    ]
