# Generated by Django 4.1.3 on 2023-10-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0008_hoteltables_hoteldrinkscartitems_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldrinkscartitems',
            name='CustomerAddress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Address'),
        ),
        migrations.AddField(
            model_name='hoteldrinkscartitems',
            name='CustomerFullName',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Customer Full Name'),
        ),
        migrations.AddField(
            model_name='hoteldrinkscartitems',
            name='PhoneNumber',
            field=models.CharField(blank=True, default='+255', max_length=14, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='hoteldrinksorderitems',
            name='CustomerAddress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Address'),
        ),
        migrations.AddField(
            model_name='hoteldrinksorderitems',
            name='CustomerFullName',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Customer Full Name'),
        ),
        migrations.AddField(
            model_name='hoteldrinksorderitems',
            name='PhoneNumber',
            field=models.CharField(blank=True, default='+255', max_length=14, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='hotelfoodcartitems',
            name='CustomerAddress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Address'),
        ),
        migrations.AddField(
            model_name='hotelfoodcartitems',
            name='CustomerFullName',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Customer Full Name'),
        ),
        migrations.AddField(
            model_name='hotelfoodcartitems',
            name='PhoneNumber',
            field=models.CharField(blank=True, default='+255', max_length=14, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='hotelfoodorderitems',
            name='CustomerAddress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Address'),
        ),
        migrations.AddField(
            model_name='hotelfoodorderitems',
            name='CustomerFullName',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Customer Full Name'),
        ),
        migrations.AddField(
            model_name='hotelfoodorderitems',
            name='PhoneNumber',
            field=models.CharField(blank=True, default='+255', max_length=14, null=True, verbose_name='Phone Number'),
        ),
    ]
