# Generated by Django 4.1.3 on 2023-10-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0009_hoteldrinkscartitems_customeraddress_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotelfoodorder',
            table='HotelFoodOrderTable',
        ),
    ]
