# Generated by Django 4.1.3 on 2023-10-05 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0010_alter_hotelfoodorder_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantCustomers',
        ),
        migrations.DeleteModel(
            name='RetailsCustomers',
        ),
        migrations.RemoveField(
            model_name='hoteldrinkscartitems',
            name='CustomerAddress',
        ),
        migrations.RemoveField(
            model_name='hoteldrinkscartitems',
            name='CustomerFullName',
        ),
        migrations.RemoveField(
            model_name='hoteldrinkscartitems',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='hoteldrinksorderitems',
            name='CustomerAddress',
        ),
        migrations.RemoveField(
            model_name='hoteldrinksorderitems',
            name='CustomerFullName',
        ),
        migrations.RemoveField(
            model_name='hoteldrinksorderitems',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='hotelfoodcartitems',
            name='CustomerAddress',
        ),
        migrations.RemoveField(
            model_name='hotelfoodcartitems',
            name='CustomerFullName',
        ),
        migrations.RemoveField(
            model_name='hotelfoodcartitems',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='hotelfoodorderitems',
            name='CustomerAddress',
        ),
        migrations.RemoveField(
            model_name='hotelfoodorderitems',
            name='CustomerFullName',
        ),
        migrations.RemoveField(
            model_name='hotelfoodorderitems',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='hotelroomscartitems',
            name='CustomerAddress',
        ),
        migrations.RemoveField(
            model_name='hotelroomscartitems',
            name='CustomerFullName',
        ),
        migrations.RemoveField(
            model_name='hotelroomscartitems',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='hotelroomsorderitems',
            name='CustomerAddress',
        ),
        migrations.RemoveField(
            model_name='hotelroomsorderitems',
            name='CustomerFullName',
        ),
        migrations.RemoveField(
            model_name='hotelroomsorderitems',
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='hoteldrinkscartitems',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelcustomers'),
        ),
        migrations.AddField(
            model_name='hoteldrinksorderitems',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelcustomers'),
        ),
        migrations.AddField(
            model_name='hotelfoodcartitems',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelcustomers'),
        ),
        migrations.AddField(
            model_name='hotelfoodorderitems',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelcustomers'),
        ),
        migrations.AddField(
            model_name='hotelroomscartitems',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelcustomers'),
        ),
        migrations.AddField(
            model_name='hotelroomsorderitems',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelcustomers'),
        ),
    ]
